{% set name = "tkf" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tkf-{{ version }}.tar.gz
  sha256: 666a717fd1bcd87e97fae0817866c96522b29faa6c3a4a8602e8c809eeadbaa9

build:
  entry_points:
    - tkf = tkf.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - backstage
    - cyberpunk-theme <0.0.14
    - kurl
    - litedao
    - litemark
    - megawidget
    - probed
    - python >={{ python_min }}
    - shared
    - subrun
    - suggestion
    - threadom
    - tkstyle
    - tkutil
    - viewable
    - winter-theme

test:
  imports:
    - tkf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/tkf
  summary: Tkinter-based framework to build Python apps
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
